---

broker-name: &broker-name
      BROKER_APPNAME: simple-service-broker

stratos-name: &stratos-name
      STRATOS_APPNAME: stratos

consumer-name: &consumer-name
      CONSUMER_APPNAME: consumer

service-instance-name: &service-instance-name
      SERVICE_INSTANCE_NAME: simple-service-instance

cf-params: &cf-params
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))

names: &names
      << : *broker-name
      << : *stratos-name
      << : *consumer-name
      << : *service-instance-name

broker-credentials: &broker-credentials
      BROKER_USERNAME: ((broker_username))
      BROKER_PASSWORD: ((broker_password))

broker-service-info: &broker-service-info
      BROKER_SERVICE_NAME: simple-service
      BROKER_PLAN_NAME: simple-plan-1

resources:

- name: cg-customer-broker
  type: git
  source:
    uri: https://github.com/resilientscale/cg-customer-broker.git
    branch: master
    depth: 1
    paths: [simple-service-broker/*]

- name: broker-source
  type: git
  source:
    uri: https://github.com/rscale-training/simple-service-broker.git
    branch: master
    depth: 1

jobs:

- name: deploy-broker
  serial_groups: [simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
    - get: broker-source
      trigger: true
  - task: deploy
    file: cg-customer-broker/simple-service-broker/ci/tasks/deploy.yml
    params: *cf-params
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names
  - task: curl-catalog
    file: cg-customer-broker/simple-service-broker/ci/tasks/curl-catalog.yml
    params:
      << : *broker-name
      << : *broker-service-info
      << : *cf-params
      << : *broker-credentials
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names

- name: create-service-broker
  serial_groups: [simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [deploy-broker]
  - task: create-service-broker
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service-broker.yml
    params:
      << : *cf-params
      << : *broker-name
      << : *broker-credentials
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names
  - task: service-brokers
    file: cg-customer-broker/simple-service-broker/ci/tasks/service-brokers.yml
    params:
      << : *broker-name
      << : *cf-params
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names

- name: use-the-broker
  serial_groups: [simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [create-service-broker]
  - task: marketplace
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service-broker.yml
    params:
      << : *cf-params
      << : *broker-name
      << : *broker-credentials
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names
  - task: create-service
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service.yml
    params:
      << : *broker-name
      << : *service-instance-name
      << : *cf-params
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names


- name: cleanup
  serial_groups: [simple]
  plan:
  - get: cg-customer-broker
    passed: [create-service-broker]
    trigger: true
  - task: cleanup
    file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
    params:
      << : *cf-params
      << : *names
