---

broker-name: &broker-name
      BROKER_APPNAME: simple-service-broker

stratos-name: &stratos-name
      STRATOS_APPNAME: stratos

stratos-hostname: &stratos-hostname
      STRATOS_HOSTNAME: stratos-simple-service-broker

service-instance-name: &service-instance-name
      SERVICE_INSTANCE_NAME: simple-service-instance

cf-params: &cf-params
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))

cf-another-space: &cf-another-space
      CF_ANOTHER_SPACE: ((cf_another_space))

names: &names
      << : *broker-name
      << : *stratos-name
      << : *service-instance-name

broker-credentials: &broker-credentials
      BROKER_USERNAME: ((broker_username))
      BROKER_PASSWORD: ((broker_password))

broker-service-info: &broker-service-info
      BROKER_SERVICE_NAME: simple-service
      BROKER_PLAN_NAME: simple-service-plan-1

broker-zip-url: &broker-zip-url
      BROKER_ZIP_URL: "http://18f.artifacts.rscale.io.s3-website-us-west-2.amazonaws.com:80/simple-service-broker.zip"

resources:

- name: cg-customer-broker
  type: git
  source:
    uri: https://github.com/resilientscale/cg-customer-broker.git
    branch: master
    depth: 1
    paths: [simple-service-broker/*]
    username: ((github_username))
    password: ((github_password))

- name: broker-source
  type: git
  source:
    uri: https://github.com/rscale-training/simple-service-broker.git
    branch: master
    depth: 1
    username: ((github_username))
    password: ((github_password))

- name: stratos
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/stratos.git
    tag_filter: stable
    branch: v2-master
    depth: 1
    username: ((github_username))
    password: ((github_password))

- name: broker-artifact
  type: s3
  source:
    bucket: ((artifact_bucket))
    region_name: us-west-2
    versioned_file: simple-service-broker.zip
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

jobs:

- name: deploy-broker
  serial_groups: [space1]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
    - get: broker-source
      trigger: true
  - task: deploy
    file: cg-customer-broker/simple-service-broker/ci/tasks/deploy.yml
    params:
      << : *cf-params
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/simple-service-broker/ci/tasks/cleanup.yml
      params:
        << : *cf-params
        << : *names
        << : *cf-another-space
  - task: curl-catalog
    file: cg-customer-broker/simple-service-broker/ci/tasks/curl-catalog.yml
    params:
      << : *broker-name
      << : *broker-service-info
      << : *cf-params
      << : *broker-credentials
    on_failure: *cleanup-task

- name: create-service-broker
  serial_groups: [space1]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [deploy-broker]
    - get: broker-source
      trigger: true
      passed: [deploy-broker]
  - task: create-service-broker
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service-broker.yml
    params:
      << : *cf-params
      << : *broker-name
      << : *broker-credentials
    on_failure: *cleanup-task
  - task: service-brokers
    file: cg-customer-broker/simple-service-broker/ci/tasks/service-brokers.yml
    params:
      << : *broker-name
      << : *cf-params
    on_failure: *cleanup-task

- name: marketplace-via-cli
  serial_groups: [space1]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [create-service-broker]
    - get: broker-source
      trigger: true
      passed: [create-service-broker]
  - task: marketplace
    file: cg-customer-broker/simple-service-broker/ci/tasks/marketplace.yml
    params:
      << : *cf-params
      << : *broker-service-info
    on_failure: *cleanup-task

- name: another-space
  serial_groups: [space2]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [marketplace-via-cli]
    - get: broker-source
      trigger: true
      passed: [marketplace-via-cli]
  - task: create-service-broker
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service-broker-another-space.yml
    params:
      CF_ANOTHER_SPACE: ((cf_another_space))
      << : *cf-params
      << : *broker-name
      << : *broker-credentials
    on_failure: *cleanup-task
  - task: service-brokers
    file: cg-customer-broker/simple-service-broker/ci/tasks/service-brokers.yml
    params:
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_another_space))
      << : *broker-name
    on_failure: *cleanup-task

- name: create-bind-purge
  serial_groups: [space1]
  plan:
  - aggregate:
    - get: cg-customer-broker
      trigger: true
      passed: [marketplace-via-cli]
    - get: broker-source
      trigger: true
      passed: [marketplace-via-cli]
  - task: create-service
    file: cg-customer-broker/simple-service-broker/ci/tasks/create-service.yml
    params:
      << : *cf-params
      << : *broker-service-info
      << : *service-instance-name
    on_failure: *cleanup-task
  - task: bind-service
    file: cg-customer-broker/simple-service-broker/ci/tasks/bind-service.yml
    params:
      << : *cf-params
      << : *broker-name
      << : *service-instance-name
    on_failure: *cleanup-task
  - task: purge-service-instance
    file: cg-customer-broker/simple-service-broker/ci/tasks/purge-service-instance.yml
    params:
      << : *cf-params
      << : *broker-name
      << : *service-instance-name
    on_failure: *cleanup-task

- name: cleanup
  serial_groups: [space1,space2]
  plan:
  - get: cg-customer-broker
    passed: [create-bind-purge, another-space]
    trigger: true
  - *cleanup-task

- name: package-broker
  serial_groups: [space1,space2]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: broker-source
      passed: [create-bind-purge]
      trigger: true
  - task: package-broker
    file: cg-customer-broker/simple-service-broker/ci/tasks/package-broker.yml
  - put: broker-artifact
    params:
      acl: public-read
      file: output/simple-service-broker.zip

- name: verify-candidate-zip
  serial_groups: [space1,space2]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: broker-source
      passed: [package-broker]
      trigger: true
    - get: broker-artifact
      trigger: true
  - task: verify-zip
    file: cg-customer-broker/simple-service-broker/ci/tasks/verify-zip.yml
    params:
      << : *broker-zip-url

- name: deploy-stratos
  serial_groups: [stratos]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: stratos
  - task: deploy-stratos
    file: cg-customer-broker/simple-service-broker/ci/tasks/deploy-stratos.yml
    params:
      << : *cf-params
      << : *stratos-name
      << : *stratos-hostname

- name: delete-stratos
  serial_groups: [stratos]
  plan:
  - aggregate:
    - get: cg-customer-broker
      passed: [deploy-stratos]
  - task: delete-stratos
    file: cg-customer-broker/simple-service-brokerci/tasks/delete-stratos.yml
    params:
      << : *cf-params
      << : *stratos-name
