# This file is provided as a reference of the values
# expected for this pipeline.  You *could* pass these
# into fly as inputs, but we recommend instead setting
# them in credhub.
#
# PLEASE put these in credhub!
cf_api:
cf_user:
cf_password:
cf_org:
cf_space:
cf_another_space:

broker_username:
broker_password:

github_username:
github_password:

artifact_bucket:
aws_access_key_id:
aws_secret_access_key:
