---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: cg-customer-broker

run:
  path: cg-customer-broker/simple-service-broker/ci/tasks/marketplace.sh

params:
  CF_API:
  CF_USER:
  CF_PWD:
  CF_ORG:
  CF_SPACE:
  BROKER_SERVICE_NAME:
  BROKER_PLAN_NAME:
