---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: cg-customer-broker
- name: broker-source

outputs:
- name: output

run:
  path: cg-customer-broker/simple-service-broker/ci/tasks/package-broker.sh
