---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: cg-customer-broker
- name: gcp-service-broker

run:
  path: cg-customer-broker/ci/tasks/deploy-gcp-service-broker.sh

params:
  CF_API:
  CF_USER:
  CF_PWD:
  CF_ORG:
  CF_SPACE:
  ROOT_SERVICE_ACCOUNT_JSON:
