# This file is provided as a reference of the values
# expected for this pipeline.  You *could* pass these
# into fly as inputs, but we recommend instead setting
# them in credhub.
#
# PLEASE put these in credhub!

# Cloud Foundry connection information.
cf_api:
cf_user:
cf_password:
cf_org:
cf_space:

# The security user authentication information used by the broker to authentication
# requests.
security_user_name:
security_user_password:

# MySQL connection information for Broker backing DB.
db_host:
db_username:
db_password:

# Github access token
github_password:

# GCP Service Account connection information.
root_service_account_json: