---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle
    tag: latest

inputs:
- name: gcp-spanner-example
- name: cg-customer-broker

outputs:
- name: zip-files

run:
  path: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/build-gcp-spanner-example-package.sh

