---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle
    tag: latest

inputs:
- name: gcp-spanner-example
- name: cg-customer-broker

run:
  path: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/

