---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: cg-customer-broker

run:
  path: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/cleanup.sh

params:
  CF_API:
  CF_USER:
  CF_PWD:
  CF_ORG:
  CF_SPACE:
  GCP_SERVICE_BROKER_APP_NAME:
  GCP_SERVICE_BROKER_NAME:
  TUTORIAL_GCP_SPANNER_SERVICE_INSTANCE_NAME:
