---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: cg-customer-broker

run:
  path: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/create-trades-service-instance.sh

params:
  CF_API:
  CF_USER:
  CF_PWD:
  CF_ORG:
  CF_SPACE:
  TRADES_SERVICE:
  TRADES_SERVICE_PLAN:
  TUTORIAL_TRADES_SERVICE_INSTANCE_NAME:
