---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
  - gcp-spanner-example-release

run:
  path:
    cg-customer-broker/ci/tasks/exercise-gcp-spanner-service-instance.sh

params:
  CF_API:
  CF_USER:
  CF_PWD:
  CF_ORG:
  CF_SPACE:
  GCP_SPANNER_SERVICE:
  GCP_SPANNER_EXAMPLE_APP_NAME: