---
gcp-broker-manifest-params: &gcp-broker-manifest-params
      GCP_BROKER_APP_NAME: gcp-service-broker-ci
      SECURITY_USER_NAME: ((security_user_name))
      SECURITY_USER_PASSWORD: ((security_user_password))
      DB_HOST: ((db_host))
      DB_USERNAME: ((db_username))
      DB_PASSWORD: ((db_password))

cf-params: &cf-params
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))

resources:

- name: cg-customer-broker
  type: git
  source:
    uri: https://github.com/resilientscale/cg-customer-broker.git
    branch: master
    depth: 1

- name: gcp-service-broker
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
    branch: master
    depth: 1

jobs:

- name: deploy-gcp-service-broker
  serial_groups: [keep-it-simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: gcp-service-broker
  - task: deploy-gcp-service-broker
    file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/deploy-gcp-service-broker.yml
    params:
      << : *cf-params
      << : *gcp-broker-app-name
      << : *gcp-broker-manifest-params
      ROOT_SERVICE_ACCOUNT_JSON: ((root_service_account_json))
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/cleanup.yml
      params:
        << : *cf-params
        << : *gcp-broker-app-name

- name: cleanup
  serial_groups: [keep-it-simple]
  plan:
  - get: cg-customer-broker
    passed: [deploy-gcp-service-broker]
    trigger: true
  - task: cleanup
    file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/cleanup.yml
    params:
      << : *cf-params
      << : *gcp-broker-app-name
    