---
resources:

- name: cg-customer-broker
  type: git
  source:
    uri: https://github.com/resilientscale/cg-customer-broker.git
    branch: master
    depth: 1

- name: gcp-service-broker
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
    branch: master
    depth: 1

jobs:

- name: deploy-gcp-service-broker
  serial_groups: [keep-it-simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: gcp-service-broker
  - task: create-gcp-service-broker
    file: cg-customer-broker/ci/tasks/deploy-gcp-service-broker.yml
    params:
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))
      ROOT_SERVICE_ACCOUNT_JSON: ((root_service_account_json))