---
# There are some tasks that just need the broker name
gcp-broker-app-name: &gcp-broker-app-name
      GCP_BROKER_APP_NAME: gcp-service-broker-ci

# This are the creds used by the broker app when creating the service broker.
gcp-broker-app-creds: &gcp-broker-app-creds
      SECURITY_USER_NAME: ((security_user_name))
      SECURITY_USER_PASSWORD: ((security_user_password))

# Variable set in the broker manifest
gcp-broker-manifest-params: &gcp-broker-manifest-params
      << : *gcp-broker-app-name
      << : *gcp-broker-app-creds
      DB_HOST: ((db_host))
      DB_USERNAME: ((db_username))
      DB_PASSWORD: ((db_password))

gcp-service-broker-name: &gcp-service-broker-name
      GCP_SERVICE_BROKER_NAME: gcp-service-broker

# Cloud Foundry parameters
cf-params: &cf-params
      CF_API: ((cf_api))
      CF_USER: ((cf_user))
      CF_PWD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SPACE: ((cf_space))

resources:

- name: cg-customer-broker
  type: git
  source:
    uri: https://github.com/resilientscale/cg-customer-broker.git
    branch: master
    depth: 1

- name: gcp-service-broker
  type: git
  source:
    uri: https://github.com/GoogleCloudPlatform/gcp-service-broker.git
    branch: master
    depth: 1

jobs:

# Deploy the service broker as an application
- name: deploy-gcp-service-broker
  serial_groups: [keep-it-simple]
  plan:
  - aggregate:
    - get: cg-customer-broker
    - get: gcp-service-broker
  - task: deploy-gcp-service-broker
    file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/deploy-gcp-service-broker.yml
    params:
      << : *cf-params
      << : *gcp-broker-manifest-params
      ROOT_SERVICE_ACCOUNT_JSON: ((root_service_account_json))
    on_failure: &cleanup-task
      task: cleanup
      file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/cleanup.yml
      params:
        << : *cf-params
        << : *gcp-broker-app-name

# Create a service broker using the app deployed above.
- name: create-service-broker
  serial_groups: [keep-it-simple]
  plan:
  - get: cg-customer-broker
#    passed: [deploy-gcp-service-broker]
#    trigger: true
  - task: create-service-broker
    file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/create-service-broker.yml
    params:
      << : *cf-params
      << : *gcp-broker-app-name
      << : *gcp-broker-app-creds

# Cleanup all resources created by the pipeline.
#- name: cleanup
#  serial_groups: [keep-it-simple]
#  plan:
#  - get: cg-customer-broker
#    passed: [create-service-broker]
#    trigger: true
#  - task: cleanup
#    file: cg-customer-broker/ci/tasks/gcp-service-broker-tutorial/cleanup.yml
#    params:
#      << : *cf-params
#      << : *gcp-broker-app-name
    